import { FFmpeg } from '@ffmpeg/ffmpeg'
import { fetchFile } from '@ffmpeg/util'
import classWorkerURL from '@ffmpeg/ffmpeg/worker?worker&url'
import coreURL from '@ffmpeg/core?url'
import wasmURL from '@ffmpeg/core/wasm?url'

let ffmpegPromise: Promise<FFmpeg> | undefined
let compositionQueue: Promise<void> = Promise.resolve()

async function loadFFmpeg(): Promise<FFmpeg> {
  if (!ffmpegPromise) {
    ffmpegPromise = (async () => {
      const ffmpeg = new FFmpeg()
      const controller = new AbortController()
      const timeout = window.setTimeout(() => controller.abort(), 60_000)
      try {
        // `?worker&url` bundles the worker's relative imports in production.
        // Version the URL as well: immutable worker responses from older
        // deployments retain their CSP headers and still block WebAssembly.
        const workerURL = new URL(classWorkerURL, window.location.href)
        workerURL.searchParams.set('csp', 'wasm-v1')
        await ffmpeg.load({ classWorkerURL: workerURL.href, coreURL, wasmURL }, { signal: controller.signal })
      } catch (error) {
        ffmpeg.terminate()
        if (controller.signal.aborted) throw new Error('本地视频合成组件加载超时，请重试')
        // FFmpeg's worker rejects with strings, not Error instances.
        throw new Error(`本地视频合成组件加载失败：${error instanceof Error ? error.message : String(error)}`)
      } finally {
        window.clearTimeout(timeout)
      }
      return ffmpeg
    })().catch((error) => {
      ffmpegPromise = undefined
      throw error
    })
  }
  return ffmpegPromise
}

async function removeFile(ffmpeg: FFmpeg, path: string): Promise<void> {
  try {
    await ffmpeg.deleteFile(path)
  } catch {
    // A failed concat may not have created every temporary file.
  }
}

async function compose(blobs: Blob[]): Promise<Blob> {
  if (blobs.length < 2) throw new Error('至少需要两个视频片段才能合成')

  const ffmpeg = await loadFFmpeg()
  const jobId = crypto.randomUUID().replace(/-/g, '')
  const inputNames = blobs.map((_, index) => `${jobId}-shot-${index}.mp4`)
  const listName = `${jobId}-shots.txt`
  const outputName = `${jobId}-complete.mp4`

  try {
    for (let index = 0; index < blobs.length; index++) {
      await ffmpeg.writeFile(inputNames[index], await fetchFile(blobs[index]))
    }
    await ffmpeg.writeFile(listName, inputNames.map(name => `file '${name}'`).join('\n'))

    const concatArgs = [
      '-f', 'concat',
      '-safe', '0',
      '-i', listName,
      '-movflags', '+faststart',
      outputName,
    ]

    // Segments generated by the provider can carry slightly different
    // timestamps, audio tracks, or codec metadata. Stream-copy concatenation
    // is fast but rejects those otherwise valid clips, so retry with a small
    // transcode when the strict path fails.
    let exitCode = await ffmpeg.exec([...concatArgs.slice(0, 6), '-c', 'copy', ...concatArgs.slice(6)])
    if (exitCode !== 0) {
      await removeFile(ffmpeg, outputName)
      exitCode = await ffmpeg.exec([
        '-f', 'concat',
        '-safe', '0',
        '-i', listName,
        '-c:v', 'libx264',
        '-preset', 'ultrafast',
        '-pix_fmt', 'yuv420p',
        '-c:a', 'aac',
        '-ar', '48000',
        '-movflags', '+faststart',
        outputName,
      ])
    }
    if (exitCode !== 0) throw new Error(`视频合成失败（FFmpeg ${exitCode}）`)

    const output = await ffmpeg.readFile(outputName)
    if (typeof output === 'string' || output.byteLength === 0) throw new Error('合成后的视频内容为空')
    const bytes = new Uint8Array(output.byteLength)
    bytes.set(output)
    return new Blob([bytes], { type: 'video/mp4' })
  } finally {
    await Promise.all([
      ...inputNames.map(name => removeFile(ffmpeg, name)),
      removeFile(ffmpeg, listName),
      removeFile(ffmpeg, outputName),
    ])
  }
}

export function composeVideoSegments(blobs: Blob[]): Promise<Blob> {
  const composition = compositionQueue.then(() => compose(blobs))
  compositionQueue = composition.then(() => undefined, () => undefined)
  return composition
}
